"""Task 3.8 — reproduce the published H₀ simulation, as a correctness check on our engine.

Every number this project has reported for H₀ comes from :mod:`fantasy_gm.draft.replay`, which
measures a *different quantity* from the one the paper reports. Before concluding that the
published method does not work on real data, we have to know that our implementation of it
reproduces the published result in the published setting. That is what this module is for.

**The published experiment** (Rosenof, *Dynamic quantification of player value for fantasy
basketball*, arXiv:2409.09884):

* one H₀ drafter against **eleven G-score drafters**, twelve teams, thirteen rounds, snake;
* each simulated season is **twenty weeks**, generated by resampling each player's own real
  weekly performances (injured weeks excluded);
* the drafters know the true distributions exactly — there is no projection error, so the only
  thing under test is the drafting;
* the reported statistic is **the share of seasons the H₀ team finishes first**, against a
  chance baseline of 1/12 = 8.3%. Published: **21.8% (Each Category), 37.7% (Most Categories)**,
  averaged over the twelve draft seats.

**What our replay harness measures instead**: category win rate for H₀ seated alongside a
G-score board, a z-score board and nine ADP bots, on one realized season, graded all-play-all.
Neither the field, the metric, the opponent model, nor the number of seasons matches. A deficit
there is not evidence against the published result until this file says whether we can produce
that result at all.

**The draft is run once per seat, not once per simulated season.** Both drafters see only the
true distributions, which do not vary between simulations, and both are deterministic — so the
rosters are identical in every one of the N seasons. Resampling the draft would burn the entire
compute budget re-deriving the same thirteen picks. The paper's thousand seasons per seat vary
the *season*, and so do ours.

**Stated deviations from the published setup**, each of which applies equally to both arms:

1. *Three seasons of weekly panels, not twenty.* We hold 2023-24 through 2025-26. Each season is
   run as its own experiment and reported separately, which is how every other table in this
   project reads.
2. *No positional eligibility.* The paper constrains rosters to a thirteen-slot position
   structure. Our draft has no positional constraint and — see ``assignment.py``, which nothing
   calls — our H₀ objective has no positional assignment term either. This is a genuine gap in
   the implementation, recorded rather than papered over.
3. *Round-robin standings.* The paper does not state its schedule. A team wins its season by
   topping the standings of a rotating round-robin: total category wins under Each Category,
   total matchup wins under Most Categories. Ties split the title.
"""

from __future__ import annotations

import json
import random
from collections import defaultdict
from concurrent.futures import ProcessPoolExecutor
from dataclasses import dataclass, field
from datetime import date
from statistics import fmean, median, pstdev

from fantasy_gm.config import CATEGORY_DIRECTION, DEFAULT_CATEGORIES, PERCENTAGE_CATEGORIES
from fantasy_gm.draft.assignment import starting_lineup
from fantasy_gm.draft.hscore import HScoreEngine, OpponentModel
from fantasy_gm.draft.opponents import AdpBot, derive_adp_order
from fantasy_gm.draft.replay import (
    bot_strategy,
    hscore_strategy,
    round_robin_pairings,
    snake_draft,
    static_order_strategy,
)
from fantasy_gm.draft.settings import DraftSettings, Objective, slot_eligibility
from fantasy_gm.draft.xscore import (
    DEFAULT_KAPPA,
    CategoryBasis,
    PeriodStats,
    VarianceMode,
    XScoreBasis,
)
from fantasy_gm.valuation import rosterable_pool

# Engine configurations under test. Three places where our implementation departs from the
# published specification, each switchable so it is measured rather than argued about:
#
#   * ``future_from_shortlist`` — the shipped engine draws future picks from the forty-man
#     candidate shortlist rather than the remaining pool. Measured first, because it looked
#     like the obvious defect: it is worth about 1%, because at the shipped softmax temperature
#     nearly all the mass sits on the top of the board whatever else is in the bag.
#   * ``future_slices`` — the shipped engine prices one future pick and multiplies by how many
#     are left, so a thirteenth-round pick is worth a third-round pick. Measured, it expects
#     every remaining round to land around the 25th-best player on the board and over-values
#     its own future production by about a third. This is the real gap the first hypothesis was
#     standing in front of.
#   * ``normalise_weights`` — the paper renormalises the strategy weights after each gradient
#     step; the shipped engine only clips them, leaving the weight scale and the softmax
#     temperature as one knob entered twice.
ARMS: dict[str, dict[str, object]] = {
    "g_score": {},                                                    # the null
    "h_score": {},                                                    # exactly as shipped
    "h_full_pool": {"future_from_shortlist": False},
    "h_normalised": {"normalise_weights": True},
    "h_fullpool_normalised": {"future_from_shortlist": False, "normalise_weights": True},
    "h_future_slices": {"future_from_shortlist": False, "future_slices": True},
    "h_paper": {
        "future_from_shortlist": False, "future_slices": True, "normalise_weights": True
    },
}

PAPER_EACH_CATEGORY = 0.218
PAPER_MOST_CATEGORIES = 0.377
MIN_PANEL_WEEKS = 10        # the paper's inclusion rule
SEASON_WEEKS = 20           # the paper's season length


def _iso_week(day: str) -> str:
    y, w, _ = date.fromisoformat(day).isocalendar()
    return f"{y}-W{w:02d}"


# --- the weekly panel ---------------------------------------------------------


@dataclass
class WeeklyPanel:
    """Each player's real weekly stat lines — the population a simulated season resamples.

    **Played weeks only, by default.** The paper excludes injured weeks and resamples from what
    is left, so a simulated season gives every player twenty *healthy* weeks. That is
    deliberately unlike :func:`fantasy_gm.draft.xscore.measure_period_stats`, which counts idle
    weeks as zeros because a realized season charges them to the manager. For the correctness
    check of task 3.8 that is the right call — the point is to isolate the optimizer from
    everything else this project has measured.

    ``build_panel(..., include_idle_weeks=True)`` puts availability back in, using the same
    span convention as ``measure_period_stats``: weeks between a player's first and last
    appearance in which they did not play become zero weeks, and weeks outside that span are
    not invented. That is the one axis on which the paper room and the replay room disagree
    most sharply, and it is the whole reason this flag exists — see
    :mod:`scripts.room_decomposition`.

    ``played`` records how many of a player's weeks were actually played, so the paper's
    ten-week inclusion rule keeps meaning ten *played* weeks under either setting.
    """

    weeks: dict[str, list[dict[str, float]]] = field(default_factory=dict)
    played: dict[str, int] = field(default_factory=dict)

    def eligible(self, min_weeks: int = MIN_PANEL_WEEKS) -> list[str]:
        return sorted(
            p for p, w in self.weeks.items()
            if self.played.get(p, len(w)) >= min_weeks
        )


def build_panel(
    store,
    season: str,
    categories: list[str] | None = None,
    include_idle_weeks: bool = False,
) -> WeeklyPanel:
    """Aggregate real box scores into per-player, per-week component totals."""
    categories = list(categories or DEFAULT_CATEGORIES)
    needed: set[str] = set()
    for c in categories:
        if c in PERCENTAGE_CATEGORIES:
            needed.update(PERCENTAGE_CATEGORIES[c])
        else:
            needed.add(c)

    acc: dict[str, dict[str, dict[str, float]]] = defaultdict(lambda: defaultdict(dict))
    for r in store.conn.execute(
        "SELECT player_id, game_date, stats_json FROM player_logs WHERE season = ?", (season,)
    ):
        stats = json.loads(r["stats_json"])
        wk = acc[r["player_id"]][_iso_week(r["game_date"])]
        for k in needed:
            wk[k] = wk.get(k, 0.0) + float(stats.get(k, 0.0))

    played = {pid: len(by_week) for pid, by_week in acc.items()}
    if not include_idle_weeks:
        return WeeklyPanel(
            {pid: [by_week[w] for w in sorted(by_week)] for pid, by_week in acc.items()},
            played,
        )

    all_weeks = sorted({w for by_week in acc.values() for w in by_week})
    weeks: dict[str, list[dict[str, float]]] = {}
    for pid, by_week in acc.items():
        active = sorted(by_week)
        span = [w for w in all_weeks if active[0] <= w <= active[-1]]
        # An idle week is an empty line, not a missing one: every downstream reader takes
        # components with ``.get(k, 0.0)``, so an empty dict is a genuine zero in every
        # counting category and zero *impact* in every percentage category.
        weeks[pid] = [by_week.get(w, {}) for w in span]
    return WeeklyPanel(weeks, played)


def basis_from_panel(
    panel: WeeklyPanel,
    pool: list[str],
    categories: list[str] | None = None,
    kappa: float = DEFAULT_KAPPA,
    mode: VarianceMode = VarianceMode.MEASURED,
) -> XScoreBasis:
    """The standardisation basis the drafters see — measured on the same panel the season is
    drawn from, so the drafters' knowledge of the distributions is *exact*, as the paper
    assumes. Any gap this experiment finds is therefore the algorithm, not the projection.
    """
    categories = list(categories or DEFAULT_CATEGORIES)
    counting = [c for c in categories if c not in PERCENTAGE_CATEGORIES]
    pcts = [c for c in categories if c in PERCENTAGE_CATEGORIES]

    league_rates: dict[str, float] = {}
    for c in pcts:
        mk, at = PERCENTAGE_CATEGORIES[c]
        made = att = 0.0
        for pid in pool:
            for wk in panel.weeks.get(pid, []):
                made += wk.get(mk, 0.0)
                att += wk.get(at, 0.0)
        league_rates[c] = made / att if att > 0 else 0.0

    stats: dict[str, dict[str, PeriodStats]] = {}
    for pid in pool:
        wks = panel.weeks.get(pid) or []
        if not wks:
            continue
        per_cat: dict[str, PeriodStats] = {}
        for c in counting:
            per_cat[c] = _summarise([w.get(c, 0.0) for w in wks])
        for c in pcts:
            mk, at = PERCENTAGE_CATEGORIES[c]
            rate = league_rates[c]
            per_cat[c] = _summarise([
                (w.get(mk, 0.0) / w[at] - rate) * w[at] if w.get(at, 0.0) > 0 else 0.0
                for w in wks
            ])
        stats[pid] = per_cat

    scored = [p for p in pool if p in stats]
    bases: dict[str, CategoryBasis] = {}
    for c in categories:
        means = [stats[p][c].mean for p in scored]
        taus = [stats[p][c].std for p in scored]
        bases[c] = CategoryBasis(
            category=c,
            pool_mean=fmean(means) if means else 0.0,
            pool_std=(pstdev(means) if len(means) > 1 else 0.0) or 1e-9,
            typical_tau=median(taus) if taus else 0.0,
            league_rate=league_rates.get(c, 0.0),
        )
    return XScoreBasis(
        categories=categories, bases=bases, stats=stats, pool=scored, kappa=kappa, mode=mode
    )


def _summarise(vals: list[float]) -> PeriodStats:
    if not vals:
        return PeriodStats(0.0, 0.0, 0)
    if len(vals) == 1:
        return PeriodStats(vals[0], 0.0, 1)
    return PeriodStats(fmean(vals), pstdev(vals), len(vals))


# --- simulating and grading a season -----------------------------------------


def simulate_standings(
    rosters: list[list[str]],
    panel: WeeklyPanel,
    settings: DraftSettings,
    rng: random.Random,
    n_weeks: int = SEASON_WEEKS,
    universe: list[str] | None = None,
    lineups: list[list[str]] | None = None,
) -> tuple[list[float], list[float]]:
    """One simulated season. Returns ``(category_wins, matchup_wins)`` per seat.

    Each player draws ``n_weeks`` weeks with replacement from their own real weekly lines, and
    a team's week is the sum over its roster — so a team's week-to-week swing is the real,
    measured swing of the players on it, correlations within a player's own week included.

    ``lineups`` restricts scoring to a **starting lineup** per seat, the bench contributing
    nothing (task 3.14). Default ``None`` keeps the shipped behaviour — every one of the
    thirteen scores every week — so every number already in `results.md` reproduces. The
    lineup is fixed for the season rather than re-set weekly, and it is chosen from pre-season
    expected value: re-assigning on each simulated week's realized lines would be an oracle,
    and it would be a *worse* oracle here than elsewhere, because the weeks are resampled and
    a manager cannot see a resample coming. It understates a real manager, who does move
    people on news; that error lands on both arms and the null carries it.

    Drawing is unaffected — the common-random-number universe is still built over full
    rosters — so a lineup arm and its null stay paired week for week.

    ``universe`` is the **common random numbers** hook, and it is not optional in practice. The
    quantity being estimated is a *difference* between two arms whose rosters overlap in twelve
    of thirteen teams, and the season-to-season noise on either arm alone is several times that
    difference. Drawing over a fixed, sorted universe rather than over whichever players
    happened to be rostered makes player X's twenty weeks identical in both arms under the same
    seed, so the shared noise cancels in the difference instead of being estimated away.
    """
    cats = settings.categories
    n = len(rosters)
    order = universe if universe is not None else sorted({p for r in rosters for p in r})
    drawn = draw_weeks(panel, order, n_weeks, rng)
    for roster in rosters:
        for pid in roster:
            if pid not in drawn:
                drawn.update(draw_weeks(panel, [pid], n_weeks, rng))

    cat_wins = [0.0] * n
    matchup_wins = [0.0] * n
    for wi in range(n_weeks):
        scoring = lineups if lineups is not None else rosters
        week_tot = [_roster_week(r, drawn, wi, cats) for r in scoring]
        for a, b in round_robin_pairings(n, wi):
            won_a = 0.0
            for c in cats:
                va, vb = week_tot[a][c], week_tot[b][c]
                direction = 1 if c in PERCENTAGE_CATEGORIES else CATEGORY_DIRECTION[c]
                pa = 0.5 if va == vb else (1.0 if direction * (va - vb) > 0 else 0.0)
                won_a += pa
            cat_wins[a] += won_a
            cat_wins[b] += len(cats) - won_a
            half = len(cats) / 2.0
            res_a = 1.0 if won_a > half else (0.5 if won_a == half else 0.0)
            matchup_wins[a] += res_a
            matchup_wins[b] += 1.0 - res_a
    return cat_wins, matchup_wins


def draw_weeks(
    panel: WeeklyPanel, order: list[str], n_weeks: int, rng: random.Random
) -> dict[str, list[dict[str, float]]]:
    """Resample ``n_weeks`` weeks for each player in ``order``, drawn in that fixed order.

    The order is the whole point: consuming the random stream player-by-player over a fixed
    universe is what makes a given player's season identical between two arms under the same
    seed, which is what lets the arms be differenced instead of merely compared.
    """
    out: dict[str, list[dict[str, float]]] = {}
    for pid in order:
        wks = panel.weeks.get(pid) or [{}]
        out[pid] = [wks[rng.randrange(len(wks))] for _ in range(n_weeks)]
    return out


def _roster_week(
    roster: list[str], drawn: dict[str, list[dict[str, float]]], wi: int, cats: list[str]
) -> dict[str, float]:
    agg: dict[str, float] = defaultdict(float)
    for pid in roster:
        for k, v in drawn[pid][wi].items():
            agg[k] += v
    out: dict[str, float] = {}
    for c in cats:
        if c in PERCENTAGE_CATEGORIES:
            mk, at = PERCENTAGE_CATEGORIES[c]
            out[c] = agg[mk] / agg[at] if agg[at] > 0 else 0.0
        else:
            out[c] = agg[c]
    return out


def _titles(standing: list[float]) -> list[float]:
    """Championship credit: 1 to the top of the standings, split on a tie.

    Splitting rather than breaking ties is what keeps the chance baseline exactly 1/N — a
    tiebreaker would hand the tie to whichever seat the rule happened to favour, and this
    harness has already been bitten once by a seat artifact of exactly that shape.
    """
    best = max(standing)
    winners = [i for i, v in enumerate(standing) if v == best]
    out = [0.0] * len(standing)
    for i in winners:
        out[i] = 1.0 / len(winners)
    return out


# --- the experiment -----------------------------------------------------------


@dataclass
class SeatResult:
    seat: int
    title_rate: float          # share of simulated seasons the arm finished first
    cat_win_rate: float        # its category win rate, for continuity with results.md
    matchup_win_rate: float


@dataclass
class PaperSimResult:
    season: str
    objective: Objective
    arm: str
    n_seasons: int
    n_teams: int
    seats: list[SeatResult]

    @property
    def mean_title_rate(self) -> float:
        return fmean(s.title_rate for s in self.seats) if self.seats else 0.0

    @property
    def mean_cat_win_rate(self) -> float:
        return fmean(s.cat_win_rate for s in self.seats) if self.seats else 0.0

    @property
    def mean_matchup_win_rate(self) -> float:
        return fmean(s.matchup_win_rate for s in self.seats) if self.seats else 0.0


def _run_seat(job: tuple) -> SeatResult:
    """One draft seat, start to finish. Module-level and argument-closed so a process pool can
    pickle it — the twelve seats are wholly independent and the machine has cores idle."""
    (
        seat, arm, basis, panel, board, settings, n_seasons, seed, engine_steps,
        opponent_model, n_teams, field_order, model_the_field, eligibility,
        engine_positional,
    ) = job

    if field_order is None:
        strategies = [static_order_strategy(board) for _ in range(n_teams)]
    else:
        # One shared stream for the whole field, seeded from (seed, seat) and *not* from the
        # arm: the bots draw once per pick in snake order in both the arm room and the null
        # room, so the stream lines up pick-for-pick and the two rooms differ only through the
        # one swapped seat. Seeding per-bot instead would work equally well; seeding per-arm
        # would silently destroy the pairing this whole harness is built on.
        bot_rng = random.Random(f"field:{seed}:{seat}")
        strategies = [
            bot_strategy(AdpBot(field_order, bot_rng)) for _ in range(n_teams)
        ]
        strategies[seat] = static_order_strategy(board)
    if arm != "g_score":
        engine = HScoreEngine(
            basis, settings, steps=engine_steps, opponent_model=opponent_model,
            opponent_board=field_order if model_the_field else None,
            positional=engine_positional, eligibility=eligibility, **ARMS[arm],
        )
        strategies[seat] = hscore_strategy(engine)

    rosters = snake_draft(strategies, board, settings)
    # Every seat is graded on a starting lineup or none of them is. The bots keep drafting
    # position-blind, which is the point: whatever it costs them, it costs the null seat too,
    # and the null is what the arm is differenced against.
    lineups = None
    if eligibility is not None:
        value = {p: basis.total(p) for p in board}
        lineups = [
            list(starting_lineup(r, eligibility, settings.starting_slots, value))
            for r in rosters
        ]
    rng = random.Random(seed * 1000 + seat)
    titles = 0.0
    cat_num = cat_den = mu_num = mu_den = 0.0
    for _ in range(n_seasons):
        cat_wins, matchup_wins = simulate_standings(
            rosters, panel, settings, rng, universe=board, lineups=lineups
        )
        standing = (
            cat_wins if settings.objective is Objective.EACH_CATEGORY else matchup_wins
        )
        titles += _titles(standing)[seat]
        cat_num += cat_wins[seat]
        cat_den += sum(cat_wins) / n_teams
        mu_num += matchup_wins[seat]
        mu_den += sum(matchup_wins) / n_teams
    return SeatResult(
        seat=seat,
        title_rate=titles / n_seasons,
        # The field's own average is the denominator: every matchup is a win for somebody, so
        # the league mean is 50% by identity and a seat's rate is read against it rather than
        # against a count of decisions.
        cat_win_rate=0.5 * cat_num / cat_den if cat_den else 0.0,
        matchup_win_rate=0.5 * mu_num / mu_den if mu_den else 0.0,
    )


def run_paper_sim(
    store,
    season: str,
    *,
    objective: Objective = Objective.MOST_CATEGORIES,
    arm: str = "h_score",
    n_seasons: int = 200,
    seats: list[int] | None = None,
    seed: int = 7,
    engine_steps: int = 8,
    pool_size: int = 156,
    kappa: float = DEFAULT_KAPPA,
    variance_mode: VarianceMode = VarianceMode.MEASURED,
    opponent_model: OpponentModel = OpponentModel.REPRESENTATIVE,
    n_teams: int = 12,
    n_rounds: int = 13,
    workers: int | None = None,
    field: str = "g_score",
    include_idle_weeks: bool = False,
    model_the_field: bool = False,
    positional: bool = False,
    engine_positional: bool = True,
    positions_asof: str = "2026-08-17",
) -> PaperSimResult:
    """One arm against eleven opponents, over every draft seat.

    ``arm`` names an entry in :data:`ARMS`. ``"g_score"`` is the **null**: the same seat drafted
    by a G-score board instead. Pooled over seats the null's title rate is 1/12 by construction
    in a G-score field, and its *per-seat* spread is the seat effect — which has to be measured
    before any seat-level reading of an H₀ row is trusted, because a snake over thirteen rounds
    is not seat-neutral even when every drafter runs the same board.

    ``field`` selects the other eleven seats: ``"g_score"`` is the published setup, ``"adp"``
    fills them with ADP bots as :mod:`fantasy_gm.draft.replay` does. ``include_idle_weeks``
    charges missed weeks to the manager. Both default to the published setting, so every number
    already recorded for task 3.8 is reproduced unchanged; they exist so the disagreement
    between this room and the replay room can be decomposed one axis at a time.

    Note that in an ADP field the null's pooled title rate is **not** 1/12 — a G-score board
    among ADP bots is a better team than a bot, so it wins more than its share. That is exactly
    why the null is differenced rather than compared to chance.

    ``model_the_field`` hands the engine the field's own board as its model of what opponents
    will take, instead of the shipped assumption that they draft best-available on ours. It is
    a no-op in a G-score field, where the two boards are already the same. In an ADP field it
    is the whole experiment: the decomposition found that H₀'s deficit is entirely about who
    else is drafting, and this asks whether *telling it who else is drafting* is the fix.

    ``positional`` turns on task 3.14 **grading**: every seat fields a starting lineup and the
    bench scores nothing. Players the store has no position for are dropped from the pool, so
    both arms draft the same board; inventing eligibility for them would put a thumb on the
    scale of this exact experiment.

    ``engine_positional`` decides separately whether the H₀ arm *optimises* over that lineup.
    Both on is the change; grading on with the engine off is the control that says how much of
    any gap is the objective term rather than the grading, and it is the cell that tells a
    finding apart from an artifact. The engine flag does nothing without the grading flag —
    an engine keeping flex slots open while the grader still counts the bench would be
    optimising a quantity nothing measures, so that combination is refused rather than run.
    """
    if model_the_field and field == "g_score":
        raise ValueError(
            "model_the_field is a no-op in a g_score field: the engine already models "
            "opponents as drafting our board. Pass field='adp' for the experiment."
        )
    if arm not in ARMS:
        raise ValueError(f"unknown arm: {arm} (known: {sorted(ARMS)})")
    if field not in ("g_score", "adp"):
        raise ValueError(f"unknown field: {field} (known: g_score, adp)")
    settings = DraftSettings(
        categories=list(DEFAULT_CATEGORIES),
        n_teams=n_teams,
        objective=objective,
        rounds=n_rounds,
    )
    panel = build_panel(
        store, season, settings.categories, include_idle_weeks=include_idle_weeks
    )
    # The pool must hold at least one player per pick, so the panel's ten-week inclusion rule
    # is applied *before* truncation rather than after — filtering a 156-man list down to 144
    # would leave a thirteen-round twelve-team draft twelve picks short.
    eligible = set(panel.eligible())
    ranked = rosterable_pool(store, season, pool_size=pool_size * 3)
    keep = [p for p in ranked if p in eligible]

    listed: dict[str, frozenset[str]] = {}
    if positional:
        # Players the store never listed are dropped *before* the pool is truncated, not after,
        # so a positional run still drafts from a full ``pool_size`` board. Truncating first
        # would quietly hand the positional arms a smaller pool than the blind ones and make
        # the two incomparable. Dropping rather than defaulting is the point: inventing an
        # eligibility for an unlisted player puts a thumb on the scale of this exact
        # experiment (the `derive_adp_order` lesson, task 3.16).
        listed, _unlisted = slot_eligibility(store.player_positions_asof(positions_asof), keep)
        keep = [p for p in keep if p in listed]

    pool = keep[:pool_size]
    if len(pool) < n_teams * n_rounds:
        raise ValueError(f"{season}: pool of {len(pool)} cannot fill {n_teams * n_rounds} picks")
    basis = basis_from_panel(panel, pool, settings.categories, kappa=kappa, mode=variance_mode)
    board = sorted(basis.pool, key=lambda p: (-basis.total(p), p))
    eligibility = {p: listed[p] for p in board} if positional else None

    field_order = derive_adp_order(store, season) if field == "adp" else None

    seats = seats if seats is not None else list(range(n_teams))
    jobs = [
        (seat, arm, basis, panel, board, settings, n_seasons, seed, engine_steps,
         opponent_model, n_teams, field_order, model_the_field, eligibility,
         bool(positional and engine_positional))
        for seat in seats
    ]
    if len(jobs) == 1:
        out = [_run_seat(jobs[0])]
    else:
        with ProcessPoolExecutor(max_workers=workers) as pool_exec:
            out = sorted(pool_exec.map(_run_seat, jobs), key=lambda r: r.seat)
    return PaperSimResult(
        season=season, objective=objective, arm=arm, n_seasons=n_seasons,
        n_teams=n_teams, seats=out,
    )


def format_paper_sim(results: list[PaperSimResult]) -> str:
    lines = [
        f"{'season':<9} {'objective':<16} {'arm':<9} {'title%':>8} {'chance%':>8} "
        f"{'cat%':>7} {'matchup%':>9}"
    ]
    for r in results:
        chance = 100.0 / r.n_teams
        lines.append(
            f"{r.season:<9} {r.objective.value:<16} {r.arm:<9} "
            f"{100 * r.mean_title_rate:>7.1f}% {chance:>7.1f}% "
            f"{100 * r.mean_cat_win_rate:>6.1f}% {100 * r.mean_matchup_win_rate:>8.1f}%"
        )
    return "\n".join(lines)
